name: Generate Pacman Contribution Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # updates twice a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: heizelannjoseph
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
